<a href="https://colab.research.google.com/github/TadakaSuryaTeja/PyTorch/blob/main/PyTorch_Basics_part_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
""" 
# To install in anaconda 

Pytorch official link https://pytorch.org/get-started/locally/
!conda install pytorch torchvision torchaudio cudatoolkit=10.2 -c pytorch
"""

/bin/bash: conda: command not found


In [ ]:
# Creating tensor
def describe(x):
    print("Type: {}".format(x.type()))
    print("Shape/size: {}".format(x.shape))
    print("Values: \n{}".format(x))

In [ ]:
import torch
describe(torch.Tensor(2, 3))

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[3.3444e-35, 0.0000e+00, 3.7835e-44],
        [0.0000e+00,        nan, 0.0000e+00]])


In [ ]:
import torch
describe(torch.rand(2, 3)) # uniform random
describe(torch.randn(2, 3)) # random normal

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0.5467, 0.0956, 0.7057],
        [0.3960, 0.2025, 0.8152]])
Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[ 0.0472,  0.7901,  0.4005],
        [ 0.1304,  2.0473, -0.3081]])
